/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifms.exemplos.view;

import br.edu.ifms.exemplos.controller.AbstractController;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.List;
import java.util.Map;
import javax.swing.KeyStroke;

/**
 *
 * @author gin
 */
public class ExemploMenu extends AbstractView {
    private String name = "Cousine";
    private int estilo = Font.PLAIN;
    private AbstractController controller;
    /**
     * Creates new form ExemploMenu
     */
    public ExemploMenu() {
        initComponents();
        
       getContentPane().setBackground(Color.orange);
        
       TratadorFonte t1 = new TratadorFonte();
       TratadorEstilo t2 = new TratadorEstilo();
       
       radCalibri.addActionListener(t1);
       radCousine.addActionListener(t1);
       chkItalico.addActionListener(t2);
       chkNegrito.addActionListener(t2);
       
       
    }

    @Override
    public void registerController(AbstractController ac) {
        this.controller = ac;
        menuCadastroLivro.addActionListener(controller);
    }
    
    private class TratadorFonte implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent ae) {
            
            name = ae.getActionCommand();
            

            Font f = new Font(name, estilo, 70);
            lblAmostra.setFont(f );
        }
        
    }
    
    private class TratadorEstilo implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent ae) {
            
            int estilo = Font.PLAIN;
            

            if(chkItalico.isSelected())
                estilo += Font.ITALIC;
            
            if(chkNegrito.isSelected())
                estilo += Font.BOLD;
            
            
            Font f = new Font(name, estilo, 70);
            lblAmostra.setFont(f );
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpfonte = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        Cor = new javax.swing.JMenu();
        Vermelho = new javax.swing.JRadioButtonMenuItem();
        Fonte = new javax.swing.JMenu();
        Exemplo = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        grpCor = new javax.swing.ButtonGroup();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        lblAmostra = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();
        radCousine = new javax.swing.JRadioButtonMenuItem();
        radCalibri = new javax.swing.JRadioButtonMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        chkNegrito = new javax.swing.JCheckBoxMenuItem();
        chkItalico = new javax.swing.JCheckBoxMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuCadastroLivro = new javax.swing.JMenuItem();

        Cor.setText("jMenu5");

        Vermelho.setSelected(true);
        Vermelho.setText("jRadioButtonMenuItem3");
        Cor.add(Vermelho);

        jPopupMenu1.add(Cor);

        Fonte.setText("jMenu5");

        Exemplo.setText("jMenuItem1");
        Fonte.add(Exemplo);

        jPopupMenu1.add(Fonte);

        jMenu8.setText("jMenu8");

        jMenuItem3.setText("Clique aqui");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem3);

        jPopupMenu1.add(jMenu8);

        jMenu6.setText("jMenu6");

        jMenu7.setText("jMenu7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.selectionBackground"));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        lblAmostra.setFont(new java.awt.Font("DejaVu Sans", 0, 70)); // NOI18N
        lblAmostra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAmostra.setText("Amostra");
        lblAmostra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblAmostraMousePressed(evt);
            }
        });
        getContentPane().add(lblAmostra, java.awt.BorderLayout.CENTER);

        jMenu3.setMnemonic('A');
        jMenu3.setText("Arquivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setMnemonic('F');
        jMenuItem1.setText("Fechar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        jMenu4.setMnemonic('E');
        jMenu4.setText("Editar");

        jMenu1.setText("Cor");

        grpCor.add(jRadioButtonMenuItem1);
        jRadioButtonMenuItem1.setText("Vermelho");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jRadioButtonMenuItem1);

        grpCor.add(jRadioButtonMenuItem2);
        jRadioButtonMenuItem2.setText("Verde");
        jRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jRadioButtonMenuItem2);

        grpCor.add(jRadioButtonMenuItem3);
        jRadioButtonMenuItem3.setText("Azul");
        jRadioButtonMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jRadioButtonMenuItem3);

        jMenu4.add(jMenu1);

        jMenu2.setText("Fonte");

        grpfonte.add(radCousine);
        radCousine.setSelected(true);
        radCousine.setText("Cousine");
        radCousine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radCousineActionPerformed(evt);
            }
        });
        jMenu2.add(radCousine);

        grpfonte.add(radCalibri);
        radCalibri.setText("Calibri");
        radCalibri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radCalibriActionPerformed(evt);
            }
        });
        jMenu2.add(radCalibri);
        jMenu2.add(jSeparator1);

        chkNegrito.setSelected(true);
        chkNegrito.setText("Negrito");
        jMenu2.add(chkNegrito);

        chkItalico.setText("Itálico");
        chkItalico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkItalicoActionPerformed(evt);
            }
        });
        jMenu2.add(chkItalico);

        jMenu4.add(jMenu2);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Cadastro");

        menuCadastroLivro.setMnemonic('l');
        menuCadastroLivro.setText("Livros");
        menuCadastroLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroLivroActionPerformed(evt);
            }
        });
        jMenu5.add(menuCadastroLivro);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        lblAmostra.setForeground(Color.red);
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    private void radCousineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radCousineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radCousineActionPerformed

    private void jRadioButtonMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem2ActionPerformed
        lblAmostra.setForeground(Color.green);
    }//GEN-LAST:event_jRadioButtonMenuItem2ActionPerformed

    private void jRadioButtonMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem3ActionPerformed
        lblAmostra.setForeground(Color.blue);
    }//GEN-LAST:event_jRadioButtonMenuItem3ActionPerformed

    private void chkItalicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkItalicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkItalicoActionPerformed

    private void radCalibriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radCalibriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radCalibriActionPerformed

    private void menuCadastroLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroLivroActionPerformed
//        LivroCadastro newWindow = new LivroCadastro();
//        newWindow.setVisible(true);
//        
//        this.setVisible(false);
    }//GEN-LAST:event_menuCadastroLivroActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void lblAmostraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAmostraMousePressed
        // TODO add your handling code here:
        if( evt.isPopupTrigger() ){
            jPopupMenu1.show(evt.getComponent(), evt.getX() , evt.getY() );
        }
    }//GEN-LAST:event_lblAmostraMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExemploMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExemploMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExemploMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExemploMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExemploMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Cor;
    private javax.swing.JMenuItem Exemplo;
    private javax.swing.JMenu Fonte;
    private javax.swing.JRadioButtonMenuItem Vermelho;
    private javax.swing.JCheckBoxMenuItem chkItalico;
    private javax.swing.JCheckBoxMenuItem chkNegrito;
    private javax.swing.ButtonGroup grpCor;
    private javax.swing.ButtonGroup grpfonte;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblAmostra;
    private javax.swing.JMenuItem menuCadastroLivro;
    private javax.swing.JRadioButtonMenuItem radCalibri;
    private javax.swing.JRadioButtonMenuItem radCousine;
    // End of variables declaration//GEN-END:variables
}
